global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'promswarm'

rule_files:
  - "swarm_node.rules.yml"
  - "swarm_task.rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dockerd-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.dockerd-exporter'
      type: 'A'
      port: 9323

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8088

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'themis-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    dns_sd_configs:
    - names:
      - 'tasks.themis-sourcedata'
      - 'tasks.themis-gateway'
      - 'tasks.themis-rules-engine'
      type: A
      port: 8080
    relabel_configs:
    - source_labels: ['__meta_dns_name']
      target_label: 'service'     


